### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Trivernis** [Trivernis/whooshy#11]
# Ideas

## General

- [x] WebSockets

## Bingo

- [x] game session with one admin
- [x] score for each player
- [x] chat commands
- [x] option to change username
- [x] display winner in chat
- [x] if username is changed, send info message in chat (" 'Trivernis' changed username to 'Silvovo'")
- [x] chat notification
- [ ] toggle word multiple times before it counts
- [ ] vote if word was heared
- [ ] statistics for word count
- [ ] linebreaks in chat (not more than two)
- [ ] chat emoji autocomplete
- [ ] show number of players

**Comment by TheSilvovo** [comment]
- show number of players
- option to change username
- if username is changed, send info message in chat (" *'Trivernis' changed username to 'Arkan'*")
